server.port=9090

spring.datasource.url=jdbc:mysql://revhire-db.cd8o0gumo35w.us-east-2.rds.amazonaws.com:3306/RevHire_new?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=121143225
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect